---
kind: pipeline
name: Image Builds 
steps:
#- name: restore
#  image: plugins/s3-cache
#  settings:
#    pull: true
#    endpoint: 
#      from_secret: s3_server_internal
#    access_key: 
#      from_secret: s3_access_key
#    secret_key: 
#      from_secret: s3_secret_key
#    restore: true


- name: Release Images
  image: ubuntu
  commands:
  - apt update && apt install gnupg
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
  - apt-add-repository https://cli.github.com/packages
  - apt update
  - apt install bash curl jq gh
  - ls -lah
  - gh -h 
  environment:
    GITHUB_TOKEN:
      from_secret: "github_api_token"


#- name: Build Images
#  image: alpine
#  commands:
#  - apk update && apk add git bash curl jq qemu gzip qemu-system-x86_64 qemu-img 
#  - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing packer
#  - bash ./build.sh


trigger:
  event:
  - push
  branch:
  - main
  - kkl
  - drone

#node:
#  location: glk
