---
kind: pipeline
name: flatcar-build
steps:
- name: Release Images
  image: alpine
  commands:
  - apk update && apk add git bash curl jq qemu gzip qemu-system-x86_64 
  - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing packer
  - bash ./build.sh
  environment:
    GITHUB_TOKEN:
      from_secret: "github_api_token"
trigger:
  event:
  - push
  branch:
  - main
  - kkl

