---
kind: pipeline
name: flatcar-build
steps:
- name: Release Images
  image: alpine
  commands:
  - apk update && apk add git bash curl jq qemu gzip
  - bash ./build.sh
  environment:
    GITHUB_TOKEN:
      from_secret: "github_api_token"
trigger:
  event:
  - push
  branch:
  - main
  - kkl

