---

name: Packer

on:
  push:
    tags:
      - v*

jobs:
  packer:
    runs-on: ubuntu-16.04 
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install QEMU and run Packer 
        run: ./build.sh
