---

name: Packer

on:
  push:
    branch:
      - kkl

jobs:
  packer:
    runs-on: ubuntu-16.04 
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install QEMU and run Packer 
        run: ./build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
