---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        #      - name: Packer build
        #        uses: enr0s/packer-qemu-action@v0.1
        #        with:
        #          templateFile: 'flatcar/flatcar-linux.json'
        #          workingDir: '.'
        #      - name: Packer build
        #        uses: riznob/packer-build-action@v1.1
        #        with:
        #          templateFile: 'flatcar/flatcar-linux.json'
        #          workingDir: '.'
        #      - name: blu
        #        run: tree
        #      -
        #        name: Set up QEMU
        #        id: qemu
        #        uses: docker/setup-qemu-action@v1
        #        with:
        #          image: tonistiigi/binfmt:latest
        #          platforms: all
      - name: bla
        run: sudo apt update && sudo apt install packer qemu qemu-system -y && packer build flatcar/flatcar-linux.json 
        #      - name: sdf
        #        run: sudo apt update && sudo apt install qemu qemu-utils qemu-kvm virt-manager libvirt-daemon-system libvirt-clients bridge-utils -y && PACKER_LOG=1 packer build flatcar/flatcar-linux.json
        #      - name: Build Artifact
        #        uses: hashicorp/packer-github-actions@master
        #        with:
        #          command: build
        #          arguments: "-color=false -on-error=abort"
        #          target: flatcar/flatcar-linux.json 
        #        env:
        #          PACKER_LOG: 1
      - name: bla
        run: tree
      - name: Compress txt with gzip
        uses: coco-hkk/compress-action@v2.1
        id: step1
        with:
          file-suffix: 'qcow2'
          target-directory-path: 'output'
          compress-tool: 'gzip'
      - name:  bla
        run: tree
      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #      - name: Create GitHub release
          #        uses: Roang-zero1/github-upload-release-artifacts-action@master
          #        with:
          #          args:
          #          - output/
